### ISSUE TITLE
Editor stucks in "suggestion mode" after reset by clicking on Query/logo

### ISSUE THREAD

**Issue by psrok1** [CERT-Polska/mquery#200] opened 2020-05-20 21:48 UTC
**Environment information**
* Mquery version (from the /status page): 1.2.0 (https://github.com/CERT-Polska/mquery/commit/f5b1811ba80245eebb7841b667f1681b642f339d)
* Ursadb version (from the /status page): 1.3.2+
* Installation method:
  - [ ] Generic docker-compose
  - [x] Dev docker-compose
  - [ ] Native (from source)
  - [ ] Other (please explain)

**Reproduction Steps**

![monaco_highlighted_bug](https://user-images.githubusercontent.com/8720367/82500277-5e6aa800-9af3-11ea-93c2-fa925f109c74.gif)

**Expected behaviour**

- Refresh editor into the clean state after clicking "Query" (possible after merging #185 and #198 fixing the #158 issue)

**Actual behaviour the bug**

- Editor is locked in "suggestion" mode until Escape key is pressed or page is refreshed.

**Comment by msm-code** [comment] 2022-12-26 21:41
I can't reproduce it anymore - probably fixed with #158 or dependency bump.

**Closed by msm-code** 2022-12-26 21:41 UTC
Labels: bug
